"""learning advice

Revision ID: a7d45c7043a3
Revises: 1ec9ad47e438
Create Date: 2026-09-30 14:34:26.883526

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a7d45c7043a3"
down_revision: str | Sequence[str] | None = "1ec9ad47e438"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_advice",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("candidate_ids", postgresql.ARRAY(sa.String(length=120)), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refreshed_by_hand_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("locale IN ('en', 'zh-CN')", name=op.f("ck_learning_advice_locale")),
        sa.CheckConstraint(
            "status IN ('ai', 'no_model', 'failed', 'empty')",
            name=op.f("ck_learning_advice_status"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_learning_advice_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_learning_advice")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("learning_advice")
    # ### end Alembic commands ###
