"""kc edges

Revision ID: 3a568a1e98f8
Revises: ab322160460f
Create Date: 2026-10-08 20:56:16.509697

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a568a1e98f8"
down_revision: str | Sequence[str] | None = "ab322160460f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kc_edges",
        sa.Column("from_kc", sa.String(length=100), nullable=False),
        sa.Column("to_kc", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.CheckConstraint("kind IN ('prerequisite', 'confusable')", name=op.f("ck_kc_edges_kind")),
        sa.PrimaryKeyConstraint("from_kc", "to_kc", "kind", name=op.f("pk_kc_edges")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kc_edges")
    # ### end Alembic commands ###
