"""diagnoses

Revision ID: b1e62314d079
Revises: 3a568a1e98f8
Create Date: 2026-10-08 22:03:36.320516

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1e62314d079"
down_revision: str | Sequence[str] | None = "3a568a1e98f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diagnoses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("target_kc_ids", postgresql.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column(
            "root_causes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("evidence_upto", sa.BigInteger(), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("rules_version", sa.String(length=50), nullable=False),
        sa.Column("memory_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("language IN ('zh', 'en')", name=op.f("ck_diagnoses_language")),
        sa.CheckConstraint("trigger IN ('weekly', 'after_set')", name=op.f("ck_diagnoses_trigger")),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
            name=op.f("fk_diagnoses_memory_id_memories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_diagnoses_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnoses")),
    )
    op.create_index(
        "ix_diagnoses_user_id_created_at", "diagnoses", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_diagnoses_user_id_created_at", table_name="diagnoses")
    op.drop_table("diagnoses")
    # ### end Alembic commands ###
