"""provider connection default model

Revision ID: 9d45eb4981f9
Revises: fe27d411cdcc
Create Date: 2026-09-28 21:06:31.710826

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d45eb4981f9"
down_revision: str | Sequence[str] | None = "fe27d411cdcc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "provider_connections", sa.Column("default_model", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider_connections", "default_model")
    # ### end Alembic commands ###
