"""exercises: practice sets, items and answers; evidence and mastery columns (ADR 0021)

Revision ID: 3b9536dae2f6
Revises: 4d7a2c9e1b60
Create Date: 2026-10-02 13:29:13.790051

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

FORMATS = "'choice4', 'cloze', 'find_fix', 'transform', 'translate', 'rewrite_own'"

# revision identifiers, used by Alembic.
revision: str = "3b9536dae2f6"
down_revision: str | Sequence[str] | None = "4d7a2c9e1b60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("origin", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("kc_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "origin IN ('dashboard', 'learner', 'card', 'plan', 'prefetch')",
            name=op.f("ck_exercise_sets_origin"),
        ),
        sa.CheckConstraint(
            "status IN ('generating', 'ready', 'in_progress', 'done', 'failed')",
            name=op.f("ck_exercise_sets_status"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_exercise_sets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_sets")),
    )
    op.create_index(
        "ix_exercise_sets_user_id_created_at",
        "exercise_sets",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("set_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("kc_id", sa.String(length=100), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column(
            "ratings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("critic", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("bank_item_id", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "format IN ('choice4', 'cloze', 'find_fix', 'transform', 'translate', 'rewrite_own')",
            name=op.f("ck_exercises_format"),
        ),
        sa.CheckConstraint(
            "status IN ('ok', 'rejected', 'reported')", name=op.f("ck_exercises_status")
        ),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["exercise_sets.id"],
            name=op.f("fk_exercises_set_id_exercise_sets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_exercises_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercises")),
    )
    op.create_index(
        "ix_exercises_set_id_position", "exercises", ["set_id", "position"], unique=False
    )
    op.create_index(
        "ix_exercises_user_id_created_at", "exercises", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "attempts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.BigInteger(), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "feedback", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_attempts_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_attempts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempts")),
    )
    op.create_index("ix_attempts_exercise_id", "attempts", ["exercise_id"], unique=False)
    op.create_index(
        "ix_attempts_user_id_created_at", "attempts", ["user_id", "created_at"], unique=False
    )
    op.add_column("kc_evidence", sa.Column("format", sa.String(length=20), nullable=True))
    op.add_column("kc_evidence", sa.Column("attempt_id", sa.BigInteger(), nullable=True))
    op.create_index("ix_kc_evidence_attempt_id", "kc_evidence", ["attempt_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_kc_evidence_attempt_id_attempts"),
        "kc_evidence",
        "attempts",
        ["attempt_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "kc_mastery",
        sa.Column(
            "formats_passed",
            postgresql.ARRAY(sa.String(length=20)),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "kc_mastery",
        sa.Column("correct_span_hours", sa.Float(), server_default="0", nullable=False),
    )
    op.add_column(
        "kc_mastery", sa.Column("last_mistake_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("kc_mastery", sa.Column("mastered_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("kc_mastery", sa.Column("state", sa.SmallInteger(), nullable=True))
    op.add_column("kc_mastery", sa.Column("step", sa.SmallInteger(), nullable=True))
    op.add_column("kc_mastery", sa.Column("stability", sa.Float(), nullable=True))
    op.add_column("kc_mastery", sa.Column("difficulty", sa.Float(), nullable=True))
    op.add_column("kc_mastery", sa.Column("due", sa.DateTime(timezone=True), nullable=True))
    op.add_column("kc_mastery", sa.Column("last_review", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        "ix_kc_mastery_user_id_due",
        "kc_mastery",
        ["user_id", "due"],
        unique=False,
        postgresql_where="due IS NOT NULL",
    )
    # ### end Alembic commands ###
    # Autogenerate does not see CHECK constraints.
    op.drop_constraint(op.f("ck_kc_evidence_source"), "kc_evidence", type_="check")
    op.create_check_constraint(
        op.f("ck_kc_evidence_source"),
        "kc_evidence",
        "source IN ('chat', 'placement', 'exercise', 'writing', 'reading')",
    )
    op.create_check_constraint(
        op.f("ck_kc_evidence_format"), "kc_evidence", f"format IS NULL OR format IN ({FORMATS})"
    )
    op.create_check_constraint(
        op.f("ck_kc_evidence_format_source"),
        "kc_evidence",
        "(source = 'exercise') = (format IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_kc_mastery_state"), "kc_mastery", "state IS NULL OR state BETWEEN 1 AND 3"
    )
    op.create_check_constraint(
        op.f("ck_kc_mastery_mastered_due"), "kc_mastery", "(mastered_at IS NULL) = (due IS NULL)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_kc_mastery_mastered_due"), "kc_mastery", type_="check")
    op.drop_constraint(op.f("ck_kc_mastery_state"), "kc_mastery", type_="check")
    op.drop_constraint(op.f("ck_kc_evidence_format_source"), "kc_evidence", type_="check")
    op.drop_constraint(op.f("ck_kc_evidence_format"), "kc_evidence", type_="check")
    op.drop_constraint(op.f("ck_kc_evidence_source"), "kc_evidence", type_="check")
    # Evidence from the new sources cannot exist before this revision.
    op.execute("DELETE FROM kc_evidence WHERE source NOT IN ('chat', 'placement')")
    op.create_check_constraint(
        op.f("ck_kc_evidence_source"), "kc_evidence", "source IN ('chat', 'placement')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_kc_mastery_user_id_due", table_name="kc_mastery", postgresql_where="due IS NOT NULL"
    )
    op.drop_column("kc_mastery", "last_review")
    op.drop_column("kc_mastery", "due")
    op.drop_column("kc_mastery", "difficulty")
    op.drop_column("kc_mastery", "stability")
    op.drop_column("kc_mastery", "step")
    op.drop_column("kc_mastery", "state")
    op.drop_column("kc_mastery", "mastered_at")
    op.drop_column("kc_mastery", "last_mistake_at")
    op.drop_column("kc_mastery", "correct_span_hours")
    op.drop_column("kc_mastery", "formats_passed")
    op.drop_constraint(
        op.f("fk_kc_evidence_attempt_id_attempts"), "kc_evidence", type_="foreignkey"
    )
    op.drop_index("ix_kc_evidence_attempt_id", table_name="kc_evidence")
    op.drop_column("kc_evidence", "attempt_id")
    op.drop_column("kc_evidence", "format")
    op.drop_index("ix_attempts_user_id_created_at", table_name="attempts")
    op.drop_index("ix_attempts_exercise_id", table_name="attempts")
    op.drop_table("attempts")
    op.drop_index("ix_exercises_user_id_created_at", table_name="exercises")
    op.drop_index("ix_exercises_set_id_position", table_name="exercises")
    op.drop_table("exercises")
    op.drop_index("ix_exercise_sets_user_id_created_at", table_name="exercise_sets")
    op.drop_table("exercise_sets")
    # ### end Alembic commands ###
