"""writing submissions

Revision ID: c200596b6a4a
Revises: 72f41c4740dd
Create Date: 2026-10-02 22:46:36.230948

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c200596b6a4a"
down_revision: str | Sequence[str] | None = "72f41c4740dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "writing_submissions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("prompt", sa.Text(), server_default="", nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("corrections", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'done', 'failed')", name=op.f("ck_writing_submissions_status")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_writing_submissions_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_writing_submissions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_writing_submissions")),
    )
    op.create_index(
        "ix_writing_submissions_user_id_created_at",
        "writing_submissions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.add_column("kc_evidence", sa.Column("writing_id", sa.BigInteger(), nullable=True))
    op.create_index("ix_kc_evidence_writing_id", "kc_evidence", ["writing_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_kc_evidence_writing_id_writing_submissions"),
        "kc_evidence",
        "writing_submissions",
        ["writing_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
    # Not detected by autogenerate. No writing evidence exists before this revision.
    op.create_check_constraint(
        op.f("ck_kc_evidence_writing_source"),
        "kc_evidence",
        "(source = 'writing') = (writing_id IS NOT NULL)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Writing evidence cannot satisfy the older constraints without its submission.
    op.drop_constraint(op.f("ck_kc_evidence_writing_source"), "kc_evidence", type_="check")
    op.execute("DELETE FROM kc_evidence WHERE source = 'writing'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_kc_evidence_writing_id_writing_submissions"), "kc_evidence", type_="foreignkey"
    )
    op.drop_index("ix_kc_evidence_writing_id", table_name="kc_evidence")
    op.drop_column("kc_evidence", "writing_id")
    op.drop_index("ix_writing_submissions_user_id_created_at", table_name="writing_submissions")
    op.drop_table("writing_submissions")
    # ### end Alembic commands ###
