"""conversations focus_kc_id

Revision ID: c6350c4e826a
Revises: a7d45c7043a3
Create Date: 2026-09-30 16:34:38.483521

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6350c4e826a"
down_revision: str | Sequence[str] | None = "a7d45c7043a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("focus_kc_id", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "focus_kc_id")
    # ### end Alembic commands ###
