"""learner model tables

Revision ID: 612ac223409b
Revises: 271e03145c58
Create Date: 2026-09-29 16:59:04.203848

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "612ac223409b"
down_revision: str | Sequence[str] | None = "271e03145c58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kc_mastery",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kc_id", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("p_mastery", sa.Float(), nullable=False),
        sa.Column("observations", sa.Integer(), server_default="0", nullable=False),
        sa.Column("recog_correct", sa.Integer(), server_default="0", nullable=False),
        sa.Column("produce_correct", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_evidence_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rules_version", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('grammar', 'word')", name=op.f("ck_kc_mastery_kind")),
        sa.CheckConstraint("p_mastery BETWEEN 0 AND 1", name=op.f("ck_kc_mastery_p_mastery")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_kc_mastery_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "kc_id", name=op.f("pk_kc_mastery")),
    )
    op.create_table(
        "skill_estimates",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("skill", sa.String(length=20), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "skill IN ('listening', 'speaking', 'reading', 'writing', 'grammar', 'vocab')",
            name=op.f("ck_skill_estimates_skill"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_skill_estimates_attempts")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_skill_estimates_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "skill", name=op.f("pk_skill_estimates")),
    )
    op.create_table(
        "kc_evidence",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kc_id", sa.String(length=100), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("evidence", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("message_id", sa.String(length=64), nullable=True),
        sa.Column("error_type", sa.String(length=20), nullable=True),
        sa.Column("severity", sa.String(length=10), nullable=True),
        sa.Column("original", sa.Text(), nullable=True),
        sa.Column("correction", sa.Text(), nullable=True),
        sa.Column("l1_transfer", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "error_type IS NULL OR error_type IN ('omission', 'addition', 'wrong_form', 'wrong_choice', 'word_order')",  # noqa: E501
            name=op.f("ck_kc_evidence_error_type"),
        ),
        sa.CheckConstraint(
            "evidence IN ('recognition', 'production')", name=op.f("ck_kc_evidence_evidence")
        ),
        sa.CheckConstraint(
            "severity IS NULL OR severity IN ('low', 'medium', 'high')",
            name=op.f("ck_kc_evidence_severity"),
        ),
        sa.CheckConstraint("source IN ('chat', 'placement')", name=op.f("ck_kc_evidence_source")),
        sa.CheckConstraint(
            "correct = (error_type IS NULL) AND correct = (severity IS NULL)",
            name=op.f("ck_kc_evidence_mistake_fields"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_kc_evidence_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_kc_evidence_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kc_evidence")),
    )
    op.create_index(
        "ix_kc_evidence_user_id_created_at", "kc_evidence", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_kc_evidence_user_id_kc_id_created_at",
        "kc_evidence",
        ["user_id", "kc_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_kc_evidence_user_id_kc_id_created_at", table_name="kc_evidence")
    op.drop_index("ix_kc_evidence_user_id_created_at", table_name="kc_evidence")
    op.drop_table("kc_evidence")
    op.drop_table("skill_estimates")
    op.drop_table("kc_mastery")
    # ### end Alembic commands ###
