"""llm_usage user index

Revision ID: 1ec9ad47e438
Revises: 347f8448994f
Create Date: 2026-09-30 13:28:22.181083

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ec9ad47e438"
down_revision: str | Sequence[str] | None = "347f8448994f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_llm_usage_user_id_created_at", "llm_usage", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_llm_usage_user_id_created_at", table_name="llm_usage")
    # ### end Alembic commands ###
