"""provider connection base_url required

Revision ID: fe27d411cdcc
Revises: 0849934f390e
Create Date: 2026-09-28 14:46:55.846747

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe27d411cdcc"
down_revision: str | Sequence[str] | None = "0849934f390e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "provider_connections", "base_url", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "provider_connections", "base_url", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    # ### end Alembic commands ###
