"""writing submission words

Revision ID: b13e7f785be1
Revises: c200596b6a4a
Create Date: 2026-10-02 23:03:43.052506

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b13e7f785be1"
down_revision: str | Sequence[str] | None = "c200596b6a4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "writing_submissions",
        sa.Column("words", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("writing_submissions", "words")
    # ### end Alembic commands ###
