"""words

Revision ID: b50a63a12ed3
Revises: 4b93dd7c1f27
Create Date: 2026-09-29 19:32:17.120554

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b50a63a12ed3"
down_revision: str | Sequence[str] | None = "4b93dd7c1f27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("word", sa.String(length=100), nullable=False),
        sa.Column("phonetic", sa.String(length=100), nullable=True),
        sa.Column("translation", sa.Text(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("collins", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("oxford", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "tags", postgresql.ARRAY(sa.String(length=10)), server_default="{}", nullable=False
        ),
        sa.Column("bnc", sa.Integer(), nullable=True),
        sa.Column("frq", sa.Integer(), nullable=True),
        sa.Column("exchange", sa.String(length=300), nullable=True),
        sa.CheckConstraint("collins BETWEEN 0 AND 5", name=op.f("ck_words_collins")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_words")),
        sa.UniqueConstraint("word", name=op.f("uq_words_word")),
    )
    op.create_index("ix_words_frq", "words", ["frq"], unique=False)
    op.create_index("ix_words_tags", "words", ["tags"], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_words_tags", table_name="words", postgresql_using="gin")
    op.drop_index("ix_words_frq", table_name="words")
    op.drop_table("words")
    # ### end Alembic commands ###
