"""word audio jobs

Revision ID: ef6b9eccf722
Revises: 5ebd002ec068
Create Date: 2026-10-10 10:10:54.040361

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ef6b9eccf722"
down_revision: str | Sequence[str] | None = "5ebd002ec068"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "word_audio_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("book_id", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("voices", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requests_per_minute", sa.Integer(), nullable=False),
        sa.Column("price_per_million", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("done", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("characters", sa.Integer(), server_default="0", nullable=False),
        sa.Column("bytes", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("cursor", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.String(length=300), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'paused', 'done', 'cancelled')",
            name=op.f("ck_word_audio_jobs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_word_audio_jobs_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_word_audio_jobs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_word_audio_jobs")),
    )
    op.create_index(
        "uq_word_audio_jobs_tenant_id_active",
        "word_audio_jobs",
        ["tenant_id"],
        unique=True,
        postgresql_where="status IN ('running', 'paused')",
    )
    op.add_column("tts_audio", sa.Column("word_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_tts_audio_word_id"), "tts_audio", ["word_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_tts_audio_word_id_words"),
        "tts_audio",
        "words",
        ["word_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_tts_audio_word_id_words"), "tts_audio", type_="foreignkey")
    op.drop_index(op.f("ix_tts_audio_word_id"), table_name="tts_audio")
    op.drop_column("tts_audio", "word_id")
    op.drop_index(
        "uq_word_audio_jobs_tenant_id_active",
        table_name="word_audio_jobs",
        postgresql_where="status IN ('running', 'paused')",
    )
    op.drop_table("word_audio_jobs")
    # ### end Alembic commands ###
