"""asr route section and usage audio seconds

Revision ID: 2bc62482af09
Revises: 6a7c0c1aaf33
Create Date: 2026-09-29 01:47:24.632019

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bc62482af09"
down_revision: str | Sequence[str] | None = "6a7c0c1aaf33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm_usage", sa.Column("audio_seconds", sa.Float(), nullable=True))
    # ### end Alembic commands ###
    # Autogenerate doesn't compare CHECK constraints: speech-to-text routes (ADR 0008).
    op.drop_constraint(op.f("ck_tenant_model_routes_section"), "tenant_model_routes", type_="check")
    op.create_check_constraint(
        op.f("ck_tenant_model_routes_section"),
        "tenant_model_routes",
        "section IN ('llm', 'embedding', 'asr')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm_usage", "audio_seconds")
    # ### end Alembic commands ###
    op.execute("DELETE FROM tenant_model_routes WHERE section = 'asr'")
    op.drop_constraint(op.f("ck_tenant_model_routes_section"), "tenant_model_routes", type_="check")
    op.create_check_constraint(
        op.f("ck_tenant_model_routes_section"),
        "tenant_model_routes",
        "section IN ('llm', 'embedding')",
    )
