"""user profiles and memories

Revision ID: bfdce3bfd67d
Revises: 2bc62482af09
Create Date: 2026-09-29 14:51:17.505740

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bfdce3bfd67d"
down_revision: str | Sequence[str] | None = "2bc62482af09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("native_language", sa.String(length=50), nullable=True),
        sa.Column("occupation", sa.String(length=200), nullable=True),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("target_exam", sa.String(length=20), nullable=True),
        sa.Column(
            "interests",
            postgresql.ARRAY(sa.String(length=100)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("daily_minutes", sa.Integer(), nullable=True),
        sa.Column("explanation_language", sa.String(length=5), nullable=True),
        sa.Column("cefr_level", sa.String(length=2), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column(
            "manual_fields",
            postgresql.ARRAY(sa.String(length=50)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cefr_level IS NULL OR cefr_level IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')",
            name=op.f("ck_user_profiles_cefr_level"),
        ),
        sa.CheckConstraint(
            "explanation_language IS NULL OR explanation_language IN ('zh', 'en')",
            name=op.f("ck_user_profiles_explanation_language"),
        ),
        sa.CheckConstraint(
            "daily_minutes IS NULL OR daily_minutes BETWEEN 1 AND 600",
            name=op.f("ck_user_profiles_daily_minutes"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_profiles")),
    )
    op.create_table(
        "memories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_conversation_id", sa.Uuid(), nullable=True),
        sa.Column("embedding", Vector(), nullable=True),
        sa.Column("embedding_model", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('fact', 'episode')", name=op.f("ck_memories_kind")),
        sa.ForeignKeyConstraint(
            ["source_conversation_id"],
            ["conversations.id"],
            name=op.f("fk_memories_source_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_memories_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memories_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
    )
    op.create_index(
        "ix_memories_user_id_kind_updated_at",
        "memories",
        ["user_id", "kind", "updated_at"],
        unique=False,
    )
    op.create_index(
        "uq_memories_episode_source_conversation_id",
        "memories",
        ["source_conversation_id"],
        unique=True,
        postgresql_where="kind = 'episode'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_memories_episode_source_conversation_id",
        table_name="memories",
        postgresql_where="kind = 'episode'",
    )
    op.drop_index("ix_memories_user_id_kind_updated_at", table_name="memories")
    op.drop_table("memories")
    op.drop_table("user_profiles")
    # ### end Alembic commands ###
