"""tutor cards

Revision ID: f94026a59099
Revises: c6350c4e826a
Create Date: 2026-09-30 22:21:00.758267

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f94026a59099"
down_revision: str | Sequence[str] | None = "c6350c4e826a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tutor_cards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.String(length=64), nullable=False),
        sa.Column("tool_call_id", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("undone_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('word_book', 'learning_goal', 'practice', 'link')",
            name=op.f("ck_tutor_cards_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'applied', 'declined', 'undone', 'info')",
            name=op.f("ck_tutor_cards_status"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_tutor_cards_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_tutor_cards_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tutor_cards")),
        sa.UniqueConstraint(
            "conversation_id",
            "tool_call_id",
            name=op.f("uq_tutor_cards_conversation_id_tool_call_id"),
        ),
    )
    op.create_index(
        "ix_tutor_cards_user_id_created_at", "tutor_cards", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tutor_cards_user_id_created_at", table_name="tutor_cards")
    op.drop_table("tutor_cards")
    # ### end Alembic commands ###
