"""feeds, feed_subscriptions and articles

Revision ID: a982263b9709
Revises: 94afd2b1f522
Create Date: 2026-10-07 23:10:26.771461

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a982263b9709"
down_revision: str | Sequence[str] | None = "94afd2b1f522"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feeds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("builtin_key", sa.String(length=64), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("site_url", sa.String(length=2000), nullable=True),
        sa.Column("license", sa.String(length=20), nullable=False),
        sa.Column("etag", sa.String(length=500), nullable=True),
        sa.Column("last_modified", sa.String(length=100), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_fetch_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failures", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "license IN ('public_domain', 'cc_by', 'unknown')", name=op.f("ck_feeds_license")
        ),
        sa.CheckConstraint(
            "(tenant_id IS NULL) = (builtin_key IS NOT NULL)", name=op.f("ck_feeds_builtin")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_feeds_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_feeds_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feeds")),
    )
    op.create_index("uq_feeds_builtin_key", "feeds", ["builtin_key"], unique=True)
    op.create_index(
        "uq_feeds_tenant_id_url",
        "feeds",
        ["tenant_id", "url"],
        unique=True,
        postgresql_where="tenant_id IS NOT NULL",
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("feed_id", sa.Uuid(), nullable=False),
        sa.Column("guid", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=300), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("summary_only", sa.Boolean(), nullable=False),
        sa.Column("license", sa.String(length=20), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column(
            "tags", postgresql.ARRAY(sa.String(length=100)), server_default="{}", nullable=False
        ),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "license IN ('public_domain', 'cc_by', 'unknown')", name=op.f("ck_articles_license")
        ),
        sa.ForeignKeyConstraint(
            ["feed_id"], ["feeds.id"], name=op.f("fk_articles_feed_id_feeds"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_articles")),
        sa.UniqueConstraint("feed_id", "guid", name=op.f("uq_articles_feed_id_guid")),
    )
    op.create_index(
        "ix_articles_feed_id_published_at", "articles", ["feed_id", "published_at"], unique=False
    )
    op.create_table(
        "feed_subscriptions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("feed_id", sa.Uuid(), nullable=False),
        sa.Column("subscribed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feeds.id"],
            name=op.f("fk_feed_subscriptions_feed_id_feeds"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_feed_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "feed_id", name=op.f("pk_feed_subscriptions")),
    )
    op.create_index(
        op.f("ix_feed_subscriptions_feed_id"), "feed_subscriptions", ["feed_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feed_subscriptions_feed_id"), table_name="feed_subscriptions")
    op.drop_table("feed_subscriptions")
    op.drop_index("ix_articles_feed_id_published_at", table_name="articles")
    op.drop_table("articles")
    op.drop_index(
        "uq_feeds_tenant_id_url", table_name="feeds", postgresql_where="tenant_id IS NOT NULL"
    )
    op.drop_index("uq_feeds_builtin_key", table_name="feeds")
    op.drop_table("feeds")
    # ### end Alembic commands ###
