"""tts audio cache

Revision ID: 87ef738892c1
Revises: c8c4c75cd6e0
Create Date: 2026-10-09 22:25:43.808058

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87ef738892c1"
down_revision: str | Sequence[str] | None = "c8c4c75cd6e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tts_audio",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("connection_name", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("voice", sa.String(length=200), nullable=False),
        sa.Column("mime_type", sa.String(length=32), nullable=False),
        sa.Column("audio", sa.LargeBinary(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("pinned", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tts_audio_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tts_audio")),
        sa.UniqueConstraint("tenant_id", "key", name=op.f("uq_tts_audio_tenant_id_key")),
    )
    op.create_index(
        "ix_tts_audio_tenant_id_last_used_at",
        "tts_audio",
        ["tenant_id", "last_used_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tts_audio_tenant_id_last_used_at", table_name="tts_audio")
    op.drop_table("tts_audio")
    # ### end Alembic commands ###
