"""reading sessions

Revision ID: ab322160460f
Revises: 7aeed833bec4
Create Date: 2026-10-08 17:44:14.075095

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ab322160460f"
down_revision: str | Sequence[str] | None = "7aeed833bec4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reading_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=True),
        sa.Column("level", sa.String(length=2), nullable=False),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "level IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')", name=op.f("ck_reading_sessions_level")
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_reading_sessions_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_reading_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["article_versions.id"],
            name=op.f("fk_reading_sessions_version_id_article_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_sessions")),
        sa.UniqueConstraint(
            "user_id", "article_id", name=op.f("uq_reading_sessions_user_id_article_id")
        ),
    )
    op.create_index(
        "ix_reading_sessions_article_id", "reading_sessions", ["article_id"], unique=False
    )
    op.add_column("conversations", sa.Column("article_id", sa.BigInteger(), nullable=True))
    op.create_index(
        op.f("ix_conversations_article_id"), "conversations", ["article_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_conversations_article_id_articles"),
        "conversations",
        "articles",
        ["article_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(op.f("ck_conversations_purpose"), "conversations", type_="check")
    op.create_check_constraint(
        op.f("ck_conversations_purpose"),
        "conversations",
        "purpose IN ('planning', 'daily', 'reading')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM conversations WHERE purpose = 'reading'")
    op.drop_constraint(op.f("ck_conversations_purpose"), "conversations", type_="check")
    op.create_check_constraint(
        op.f("ck_conversations_purpose"), "conversations", "purpose IN ('planning', 'daily')"
    )
    op.drop_constraint(
        op.f("fk_conversations_article_id_articles"), "conversations", type_="foreignkey"
    )
    op.drop_index(op.f("ix_conversations_article_id"), table_name="conversations")
    op.drop_column("conversations", "article_id")
    op.drop_index("ix_reading_sessions_article_id", table_name="reading_sessions")
    op.drop_table("reading_sessions")
    # ### end Alembic commands ###
