"""conversation purpose

Revision ID: a5025a738252
Revises: f94026a59099
Create Date: 2026-09-30 22:49:22.721297

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5025a738252"
down_revision: str | Sequence[str] | None = "f94026a59099"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("purpose", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###
    # Autogenerate does not see CHECK constraints.
    op.create_check_constraint(
        op.f("ck_conversations_purpose"), "conversations", "purpose IN ('planning')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_conversations_purpose"), "conversations", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "purpose")
    # ### end Alembic commands ###
