"""placement sessions

Revision ID: 347f8448994f
Revises: 92cbcc17eefe
Create Date: 2026-09-30 00:21:26.791788

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "347f8448994f"
down_revision: str | Sequence[str] | None = "92cbcc17eefe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "placement_item_stats",
        sa.Column("item_id", sa.String(length=100), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_placement_item_stats_attempts")),
        sa.PrimaryKeyConstraint("item_id", name=op.f("pk_placement_item_stats")),
    )
    op.create_table(
        "placement_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("stage", sa.String(length=10), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("rules_version", sa.String(length=50), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'done') = (result IS NOT NULL)",
            name=op.f("ck_placement_sessions_done_result"),
        ),
        sa.CheckConstraint(
            "stage IN ('vocab', 'grammar')", name=op.f("ck_placement_sessions_stage")
        ),
        sa.CheckConstraint(
            "status IN ('in_progress', 'done', 'abandoned')",
            name=op.f("ck_placement_sessions_status"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_placement_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_placement_sessions")),
    )
    op.create_index(
        "ix_placement_sessions_user_id_created_at",
        "placement_sessions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_placement_sessions_user_id_in_progress",
        "placement_sessions",
        ["user_id"],
        unique=True,
        postgresql_where="status = 'in_progress'",
    )
    # ### end Alembic commands ###
    # Words a learner marks known from their placement result (autogenerate does not
    # see CHECK changes).
    op.drop_constraint(op.f("ck_user_cards_source"), "user_cards", type_="check")
    op.create_check_constraint(
        op.f("ck_user_cards_source"),
        "user_cards",
        "source IN ('book', 'auto', 'manual', 'placement')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM user_cards WHERE source = 'placement'")
    op.drop_constraint(op.f("ck_user_cards_source"), "user_cards", type_="check")
    op.create_check_constraint(
        op.f("ck_user_cards_source"), "user_cards", "source IN ('book', 'auto', 'manual')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_placement_sessions_user_id_in_progress",
        table_name="placement_sessions",
        postgresql_where="status = 'in_progress'",
    )
    op.drop_index("ix_placement_sessions_user_id_created_at", table_name="placement_sessions")
    op.drop_table("placement_sessions")
    op.drop_table("placement_item_stats")
    # ### end Alembic commands ###
