"""pronunciation attempts

Revision ID: deaa2ad30b74
Revises: 0bc5f9185f2b
Create Date: 2026-10-10 12:19:26.571297

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "deaa2ad30b74"
down_revision: str | Sequence[str] | None = "0bc5f9185f2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pronunciation_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=True),
        sa.Column("reference_text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("words", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recognized_text", sa.Text(), server_default="", nullable=False),
        sa.Column("audio_seconds", sa.Float(), nullable=False),
        sa.Column("fallback_reason", sa.String(length=20), nullable=True),
        sa.Column("counted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "language IN ('en-US', 'en-GB')", name=op.f("ck_pronunciation_attempts_language")
        ),
        sa.CheckConstraint(
            "provider IN ('azure', 'asr_fallback')", name=op.f("ck_pronunciation_attempts_provider")
        ),
        sa.CheckConstraint(
            "source IN ('chat', 'reading', 'vocab', 'speaking')",
            name=op.f("ck_pronunciation_attempts_source"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_pronunciation_attempts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pronunciation_attempts")),
    )
    op.create_index(
        "ix_pronunciation_attempts_user_id_created_at",
        "pronunciation_attempts",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "word_pronunciations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=False),
        sa.Column("low_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_low_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "accuracy >= 0 AND accuracy <= 100", name=op.f("ck_word_pronunciations_accuracy")
        ),
        sa.CheckConstraint("low_count >= 0", name=op.f("ck_word_pronunciations_low_count")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_word_pronunciations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
            name=op.f("fk_word_pronunciations_word_id_words"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "word_id", name=op.f("pk_word_pronunciations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("word_pronunciations")
    op.drop_index(
        "ix_pronunciation_attempts_user_id_created_at", table_name="pronunciation_attempts"
    )
    op.drop_table("pronunciation_attempts")
    # ### end Alembic commands ###
