"""daily_plans

Revision ID: 16aa2f30597e
Revises: b1e62314d079
Create Date: 2026-10-09 13:48:24.452078

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "16aa2f30597e"
down_revision: str | Sequence[str] | None = "b1e62314d079"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_KINDS = ("word_book", "learning_goal", "practice", "link", "writing")


def _kinds(names: tuple[str, ...]) -> None:
    """The tutor's daily plan proposals are cards of their own kind (task 48)."""
    op.drop_constraint(op.f("ck_tutor_cards_kind"), "tutor_cards", type_="check")
    listed = ", ".join(f"'{n}'" for n in names)
    op.create_check_constraint(op.f("ck_tutor_cards_kind"), "tutor_cards", f"kind IN ({listed})")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("choice", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("card_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('proposed', 'applied', 'declined')", name=op.f("ck_daily_plans_status")
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["tutor_cards.id"],
            name=op.f("fk_daily_plans_card_id_tutor_cards"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_daily_plans_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_plans")),
        sa.UniqueConstraint("user_id", "day", name=op.f("uq_daily_plans_user_id_day")),
    )
    # ### end Alembic commands ###
    _kinds((*_KINDS, "daily_plan"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daily_plans")
    # ### end Alembic commands ###
    op.execute("DELETE FROM tutor_cards WHERE kind = 'daily_plan'")
    _kinds(_KINDS)
