"""tts route section and usage characters

Revision ID: c8c4c75cd6e0
Revises: c7e2a94d1b05
Create Date: 2026-10-09 22:15:55.443867

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8c4c75cd6e0"
down_revision: str | Sequence[str] | None = "c7e2a94d1b05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm_usage", sa.Column("characters", sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # Autogenerate doesn't compare CHECK constraints: text-to-speech (ADR 0028).
    _section_check("'llm', 'embedding', 'asr', 'tts'")
    _kind_check("'deepseek', 'anthropic', 'openai', 'openai_compatible', 'azure_speech'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm_usage", "characters")
    # ### end Alembic commands ###
    op.execute("DELETE FROM tenant_model_routes WHERE section = 'tts'")
    _section_check("'llm', 'embedding', 'asr'")
    # Routes may still name a speech-only connection; they skip missing ones (ADR 0004).
    op.execute("DELETE FROM provider_connections WHERE kind = 'azure_speech'")
    _kind_check("'deepseek', 'anthropic', 'openai', 'openai_compatible'")


def _section_check(values: str) -> None:
    name = op.f("ck_tenant_model_routes_section")
    op.drop_constraint(name, "tenant_model_routes", type_="check")
    op.create_check_constraint(name, "tenant_model_routes", f"section IN ({values})")


def _kind_check(values: str) -> None:
    name = op.f("ck_provider_connections_kind")
    op.drop_constraint(name, "provider_connections", type_="check")
    op.create_check_constraint(name, "provider_connections", f"kind IN ({values})")
