"""tts audio user

Revision ID: 5ebd002ec068
Revises: 87ef738892c1
Create Date: 2026-10-09 23:13:23.214577

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ebd002ec068"
down_revision: str | Sequence[str] | None = "87ef738892c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tts_audio", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_tts_audio_user_id"), "tts_audio", ["user_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_tts_audio_user_id_users"),
        "tts_audio",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_tts_audio_user_id_users"), "tts_audio", type_="foreignkey")
    op.drop_index(op.f("ix_tts_audio_user_id"), table_name="tts_audio")
    op.drop_column("tts_audio", "user_id")
    # ### end Alembic commands ###
