"""speaking sessions

Revision ID: 08753b283c97
Revises: deaa2ad30b74
Create Date: 2026-10-10 14:46:55.248776

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "08753b283c97"
down_revision: str | Sequence[str] | None = "deaa2ad30b74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PURPOSES = ("planning", "daily", "reading")
_SOURCES = ("chat", "placement", "exercise", "writing", "reading")


def _set_check(table: str, column: str, values: tuple[str, ...]) -> None:
    name = op.f(f"ck_{table}_{column}")
    op.drop_constraint(name, table, type_="check")
    op.create_check_constraint(name, table, f"{column} IN ({', '.join(map(repr, values))})")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "speaking_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.String(length=40), nullable=True),
        sa.Column("mode", sa.String(length=10), server_default="cascade", nullable=False),
        sa.Column("status", sa.String(length=10), server_default="active", nullable=False),
        sa.Column("level", sa.String(length=2), nullable=False),
        sa.Column("turns", sa.Integer(), server_default="0", nullable=False),
        sa.Column("spoken_turns", sa.Integer(), server_default="0", nullable=False),
        sa.Column("spoken_seconds", sa.Float(), server_default="0", nullable=False),
        sa.Column(
            "corrected_message_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("intelligibility", sa.String(length=10), nullable=True),
        sa.Column("counted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "intelligibility IN ('hard', 'partly', 'mostly', 'fully')",
            name=op.f("ck_speaking_sessions_intelligibility"),
        ),
        sa.CheckConstraint(
            "level IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')", name=op.f("ck_speaking_sessions_level")
        ),
        sa.CheckConstraint(
            "mode IN ('cascade', 'realtime')", name=op.f("ck_speaking_sessions_mode")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'done', 'failed')", name=op.f("ck_speaking_sessions_status")
        ),
        sa.CheckConstraint("spoken_seconds >= 0", name=op.f("ck_speaking_sessions_spoken_seconds")),
        sa.CheckConstraint("turns >= 0", name=op.f("ck_speaking_sessions_turns")),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_speaking_sessions_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_speaking_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_speaking_sessions")),
        sa.UniqueConstraint("conversation_id", name=op.f("uq_speaking_sessions_conversation_id")),
    )
    op.create_index(
        "ix_speaking_sessions_user_id_started_at",
        "speaking_sessions",
        ["user_id", "started_at"],
        unique=False,
    )
    op.add_column("conversations", sa.Column("scenario_id", sa.String(length=40), nullable=True))
    # ### end Alembic commands ###
    _set_check("conversations", "purpose", (*_PURPOSES, "speaking", "realtime"))
    _set_check("kc_evidence", "source", (*_SOURCES, "speaking"))


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM kc_evidence WHERE source = 'speaking'")
    _set_check("kc_evidence", "source", _SOURCES)
    op.execute("DELETE FROM conversations WHERE purpose IN ('speaking', 'realtime')")
    _set_check("conversations", "purpose", _PURPOSES)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "scenario_id")
    op.drop_index("ix_speaking_sessions_user_id_started_at", table_name="speaking_sessions")
    op.drop_table("speaking_sessions")
    # ### end Alembic commands ###
