"""conversation reflection cursors

Revision ID: 271e03145c58
Revises: bfdce3bfd67d
Create Date: 2026-09-29 15:04:50.684155

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "271e03145c58"
down_revision: str | Sequence[str] | None = "bfdce3bfd67d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations", sa.Column("reflected_message_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "conversations", sa.Column("summarized_message_id", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "summarized_message_id")
    op.drop_column("conversations", "reflected_message_id")
    # ### end Alembic commands ###
