"""vocabulary cards

Revision ID: 92cbcc17eefe
Revises: b50a63a12ed3
Create Date: 2026-09-29 20:31:01.879888

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "92cbcc17eefe"
down_revision: str | Sequence[str] | None = "b50a63a12ed3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_cards",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("state", sa.SmallInteger(), nullable=True),
        sa.Column("step", sa.SmallInteger(), nullable=True),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("due", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_review", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('book', 'auto', 'manual')", name=op.f("ck_user_cards_source")
        ),
        sa.CheckConstraint(
            "status <> 'learning' OR due IS NOT NULL", name=op.f("ck_user_cards_learning_due")
        ),
        sa.CheckConstraint(
            "status IN ('new', 'learning', 'known', 'suspended')", name=op.f("ck_user_cards_status")
        ),
        sa.CheckConstraint(
            "state IS NULL OR state BETWEEN 1 AND 3", name=op.f("ck_user_cards_state")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_cards_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["word_id"], ["words.id"], name=op.f("fk_user_cards_word_id_words")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_cards")),
        sa.UniqueConstraint("user_id", "word_id", name=op.f("uq_user_cards_user_id_word_id")),
    )
    op.create_index(
        "ix_user_cards_user_id_due",
        "user_cards",
        ["user_id", "due"],
        unique=False,
        postgresql_where="status = 'learning'",
    )
    op.create_index(
        "ix_user_cards_user_id_first_reviewed_at",
        "user_cards",
        ["user_id", "first_reviewed_at"],
        unique=False,
    )
    op.create_table(
        "user_word_book",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.String(length=20), nullable=False),
        sa.Column("daily_new", sa.SmallInteger(), nullable=True),
        sa.Column("screen_offset", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_word_book_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_word_book")),
    )
    op.create_table(
        "review_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("card_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("review_duration_ms", sa.Integer(), nullable=True),
        sa.Column("card_before", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("card_after", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("rating BETWEEN 1 AND 4", name=op.f("ck_review_logs_rating")),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["user_cards.id"],
            name=op.f("fk_review_logs_card_id_user_cards"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_review_logs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_logs")),
    )
    op.create_index(op.f("ix_review_logs_card_id"), "review_logs", ["card_id"], unique=False)
    op.create_index(
        "ix_review_logs_user_id_reviewed_at",
        "review_logs",
        ["user_id", "reviewed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_logs_user_id_reviewed_at", table_name="review_logs")
    op.drop_index(op.f("ix_review_logs_card_id"), table_name="review_logs")
    op.drop_table("review_logs")
    op.drop_table("user_word_book")
    op.drop_index("ix_user_cards_user_id_first_reviewed_at", table_name="user_cards")
    op.drop_index(
        "ix_user_cards_user_id_due", table_name="user_cards", postgresql_where="status = 'learning'"
    )
    op.drop_table("user_cards")
    # ### end Alembic commands ###
